version: '3.7'

services:
  # 開発用
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
      - '6006:6006' # story point
    tty: true
    # init: true
    volumes:
      - ./:/app/
